### ISSUE TITLE
The error of downloing the trained models 

### ISSUE THREAD

**Issue by zhouqiuhu** [openvax/mhcflurry#116]
Hi,
When I download the trained models with the command "mhcflurry-downloads fetch", it didn't work.

Here is the error:
IOError: [Errno socket error] EOF occurred in violation of protocol (_ssl.c:661)

P.S: I could donwload those data with  browser. Where should I put the files?

**Comment by timodonnell** [comment]
Looks like a possibly transient error - try it again maybe?

You can also run `mhcflurry-downloads info` to see where to unpack it to manually. When I run this command I get:

```
(py3k) [tim@tims-macbook ~]$ mhcflurry-downloads info

... (other output) ...

Configuration
  current release                     = 0.9.2
  downloads dir                       = '/Users/tim/Library/Application Support/mhcflurry/4/0.9.2' [exists]

... (other output) ...
```

If you unpack the models_class1.tar.bz2 file into the path indicated by "downloads dir" above, it will work. E.g. on my machine:

```
(py3k) [tim@tims-macbook ~]$ ls '/Users/tim/Library/Application Support/mhcflurry/4/0.9.2/models_class1'
GENERATE.sh          LOG.txt.bz2          hyperparameters.json models
```

**Comment by zhouqiuhu** [comment]
Thanks for your help. The mhcflurry work well now.
The error is still there though. Maybe there is a problem of my system configuration.

**Comment by timodonnell** [comment]
It might be this issue, which seems to be related to having a python linked against a really old version of openssl: https://github.com/requests/requests/issues/3006

One suggestion in that thread is to try:

```
pip install --force-reinstall requests[security]
```

There's also some other suggestions in that thread. If you figure out a solution please let us know. If you find a way to modify the download code to work for you we'd be interested in that as well.

**Comment by zhouqiuhu** [comment]
Hi.
Sorry for replying late.
 I tried that code you mentioned but it didn't work neither.

**Comment by timodonnell** [comment]
Stumped on this one. Closing for now, please reopen if you continue to have an issue downloading data and models.
