### ISSUE TITLE
Does training data contain mass-spec data?

### ISSUE THREAD

**Issue by weipenegHU** [openvax/mhcflurry#121]
Hi Donnell, I am curious about if the latest version of MHCflurry is trained on both mass-spec data and binding data set

**Comment by timodonnell** [comment]
The default predictor for the current release is trained on only affinity measurements (no mass spec) but the model selection step incorporates mass spec. We also release experimental predictors whose training data directly includes mass spec though, they just aren't the default. If you want to use predictors trained directly on mass spec you can run:

```
$ mhcflurry-downloads fetch models_class1_trained_with_mass_spec
```

and then to make them used by default:

```
export MHCFLURRY_DEFAULT_CLASS1_MODELS="$(mhcflurry-downloads path models_class1_trained_with_mass_spec)/models"
```

Let me know if you have any questions. Leaving this issue open as a reminder for us to add the above to the documentation sometime soon.

**Comment by weipenegHU** [comment]
Thanks for your information
