### ISSUE TITLE
installation guide does not work - tensorflow version

### ISSUE THREAD

**Issue by tahuh** [openvax/mhcflurry#131]
Hi, 
I tried to install mhcflurry using pip on our lab server but the error raised.
I ran the installation command as a root user following the installation instruction.
The lines of errors while installation shown below.

Downloading/unpacking tensorflow>=1.1.0 (from mhcflurry)
  Could not find any downloads that satisfy the requirement tensorflow>=1.1.0 (from mhcflurry)
Cleaning up...
No distributions at all found for tensorflow>=1.1.0 (from mhcflurry)

However, our server equipped with TensorFlow with version 1.4.0 as shown below

Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> tf.__version__
'1.4.0'
>>> 

Is there any reason that the installation fails or any specific hardware specificity?
Our server system equipped with NVIDA's TITAN X as GPU card and CUDA with version 8

Thanks.

**Comment by timodonnell** [comment]
Sorry we couldn't help with this - did you get it working?
