### ISSUE TITLE
IC50 vs percentile rank

### ISSUE THREAD

**Issue by saskra** [openvax/mhcflurry#132]
If I understand correctly, you are using IC50 values. I would rather like to train and test on percentile ranks. Is this possible somehow? It seems that simply training on them still leads to IC50 like values in the evaluation which lowers the correlation and other quality measures a lot.

**Comment by timodonnell** [comment]
Yes, we're using IC50 values for training and prediction. The percentile
ranks are calibrated separately for each allele after training by
generating a histogram of IC50 values across a large number of random
peptides.

If you want to train and test on values with a different scale, it should
be an easy change though - I'd suggest just editing
https://github.com/openvax/mhcflurry/blob/master/mhcflurry/regression_target.py
to define the to_ic50 and from_ic50 functions as needed to transform your
raw values into numbers between 0.0-1.0 (for from_ic50) and the inverse
(to_ic50). If you are working with raw percentile ranks already in the
range 0.0-1.0 these could just be the identity function. Of course however
these won't necessarily be calibrated (i.e. no guarantee that 20% of random
peptides will have predictions < 0.2).

Curious how this goes for you, let me know if you run into trouble.

**Comment by saskra** [comment]
Thx! My values range from 0.1 to 100, so I changed max_ic50=5000 to 100 everywhere. Now the upper limit of the results actually is 100 as well, but the lower limit still is >1, unfortunately. Do/ can I change something to adapt that as well?

I have other subsets with other ranges of values, e.g. one where there are only good binders with values <1 - do I have to adapt for that in the source code every time, or is there a possibility to pass the limits as parameters somewhere?

**Comment by timodonnell** [comment]
We're focused on training on publicly available datasets for now but curious to hear how this went for you. Closing for now.
