### ISSUE TITLE
is mhcflurry more accurate than NetMHCpan-4.0

### ISSUE THREAD

**Issue by kobejamescurry** [openvax/mhcflurry#134]
Dear professor,
in your outstanding paper, you mentioned that 
![image](https://user-images.githubusercontent.com/46668881/51448323-d474c880-1d60-11e9-9d59-43f9f95c5ccb.png)
so does the abstract mean there is no better performance of mhcflurry than NetMHCpan-4.0 **in accuracy excluding speed.**
thanks a lot.

**Comment by timodonnell** [comment]
Hi there - this is correct. We did not see a statistically significant accuracy improvement over NetMHCpan 4.0 on our small validation set. Larger validation datasets would be needed to see an accuracy difference between the two (if there in fact is any).

**Comment by timodonnell** [comment]
Hey, if you have RNA also (which is used to pick the transcript for each mutation), you could try using [isovar](https://github.com/openvax/isovar) or, for the particular case of making a synthetic long peptide vaccine, [vaxrank](https://github.com/openvax/vaxrank). Both of these tools can use various MHC binding predictors, including NetMHC and MHCflurry. There are a number of tools developed by other groups for doing this, such as [mupexi](https://github.com/ambj/MuPeXI) and [pvacseq](https://github.com/griffithlab/pVAC-Seq). Hope this helps!

**Comment by kobejamescurry** [comment]
Thanks a lot. your answer is very useful, I am using mupexi, which the result is not easy to understand.
mine has just only dna-seq
