### ISSUE TITLE
Support arbitrary length input sequences

### ISSUE THREAD

**Issue by iskandr** [openvax/mhcflurry#156]
Just hit this error trying to predict on mass spec detected MHC ligands:

```
ValueError("23 peptides have lengths outside of supported range [5, 15]: ...")
```

What do you think of scanning 15mer subsequences across longer sequences and returning the mean [0,1] score for each component of the predictor? Taking the average rather than max would nudge those values downward, which is desirable with longer sequences.

**Comment by timodonnell** [comment]
If we need support for these peptide lengths, it may make the most sense to
just train the predictors using a max length of e.g. 17. Having an
additional secondary way support longer peptide lengths seems complicated.
But I'd be interested to know if your suggestion gives good accuracy if you
try it out.

You can also pass throw=False by the way, if you just want to get NaNs for
these peptides and not throw an error.
