### ISSUE TITLE
Regarding output

### ISSUE THREAD

**Issue by komalhpatil** [openvax/mhcflurry#157]
Hello sir,
I have tried predicting MHC binding affinity using NetMHCPAn 4.0 server and MHCFlurry both, but I'm not getting consistent results. May I please know the reason behind this issue?

**Comment by timodonnell** [comment]
NetMHCpan and MHCflurry are different predictive methods, so results will definitely be different between the two. However, if you are seeing large / consistent discrepancies in some cases we'd be interested to know about that, if you can share the peptides and alleles you're looking at. Thanks.

**Comment by komalhpatil** [comment]
Sure, thanks.
Following are a few peptides from our study,
GLLLVRPPR 
GWVIAASFPR 
GQLSCFLSPR 
YAETFSSYTDLDK 
STKIDWFDDTVSSK
