### ISSUE TITLE
how to use peptide-lengths parameter?

### ISSUE THREAD

**Issue by kloot** [openvax/mhcflurry#160]
Hi, thanks for providing this tool! 
I have trouble figuring out how to pass values with the `--peptide-lengths option` to mhcflurry-predict-scan.
`--peptide-lengths 8,9,10` results in error: argument `--peptide-lengths: invalid int value: '8,9,10'`
Various other formats result in other errors - please let me know if this is expected behavior. 
Thanks in advance!

**Comment by timodonnell** [comment]
Hi there, try passing each peptide length as a separate argument, eg:

```
mhcflurry-predict-scan  \
   --sequences MFVFLVLLPLVSSQCVNLTTRTQLPPAYTNSFTRGVYYPDKVFRSSVLHS   \
   --alleles HLA-A*02:01 \
   --peptide-lengths 8 9 10

**Comment by kloot** [comment]
Thanks for your quick reply, Tim! I can confirm your suggestion works, however 
```
mhcflurry-predict-scan \
--alleles HLA-A*02:01 \
--peptide-lengths 8 9 10 \
--input-format fasta \
input.fasta
```
throws the same error as in my original message. The parameter combination behaves as expected (works) if I omit `--peptide lengths 8 9 10`. Odd?

**Comment by kloot** [comment]
Sorry I was wrong!

**Comment by kloot** [comment]
Works:
```
mhcflurry-predict-scan \
--alleles HLA-A*02:01 \
--peptide-lengths 8 9 10 \
--input-format fasta \
input.fasta
```

Does not work:
```
mhcflurry-predict-scan \
--alleles HLA-A*02:01 \
--input-format fasta \
--peptide-lengths 8 9 10 \
input.fasta
```

A little unexpected that parameter order is important - however happy to have made it work! May thanks!

**Comment by timodonnell** [comment]
Ah i see - yes that is confusing! Probably should let it also accept a
separated list as a fix in a future version.

**Comment by kloot** [comment]
Good idea, that was my first assumption as it's consistent with --alleles. 
Thank you again for making this software available. I don't know how to add a 'question' flag, as it's not truly an 'issue' ;-)

**Comment by JamieHeather** [comment]
Maybe allowing a range might also be helpful? E.g. 8-10, or 8:10 or something.

**Comment by kloot** [comment]
If I'm allowed an off-topic suggestion for future versions: Permit lower-case characters in the input sequence and retain upper/lower case in the output. 
Lower-case letters are [FASTA-conform](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp) and will make it much easier to track mutant residues in neopeptides in the mhcflurry output.

**Comment by timodonnell** [comment]
Both sound like good ideas. Leaving this ticket open as a reminder to do these for the next version (or feel free to open separate issues)

**Comment by kloot** [comment]
Thank you in advance Tim!
