### ISSUE TITLE
MHC-flurry 1.6 use

### ISSUE THREAD

**Issue by amomin-pact** [openvax/mhcflurry#161]
Hi ,
   I was wondering if there are specific instructions to install and use MHCflurry 1.6. I see that algorithm has been modified to include peptide presentation efficiency. 

   Thanks
     Amin

**Comment by timodonnell** [comment]
Hi Amin - the 1.6.0 version is on pypi so if you `pip install mhcflurry` you should get that version. When you run `mhcflurry-predict` or `mhcflurry-predict-scan` as in the readme you will get antigen processing predictions as well as MHC affinities using this new version. Let us know if you hit any issues.

Tim

**Comment by amomin-pact** [comment]
I was able to install mhcflurry 1.6. How can I switch between 1.4 and 1.6 without switching conda environment?

   Thanks
