### ISSUE TITLE
Non available alleles

### ISSUE THREAD

**Issue by jfnavarro** [openvax/mhcflurry#165]
I have a list of HLAs predicted with HLA-LA and arcasHLA but some of them are not present in the list of available alleles. Is that expected? Or perhaps a naming issue?

**Comment by timodonnell** [comment]
Which alleles are missing? One basic possible reason is that we only support class I MHC at this point, not class II.

**Comment by jfnavarro** [comment]
Yes, I had just realised that all the missing alleles were class II after I opened the issue.
