### ISSUE TITLE
mhcflurry-downloads: command not found

### ISSUE THREAD

**Issue by simoneggenschwiler** [openvax/mhcflurry#168]
Dear mhcflurry team,

I am trying to use your predictor but I have issues when I try to download the models. After having successfully installed mhcflurry with `pip install mhcflurry`, my terminal does not find the command of mhcflurry-downloads. Do you have an idea where that might be coming from?

Thanks in advance for your time.

Best,
Simon

**Comment by timodonnell** [comment]
hmm not sure what might be causing that. What operating system are you
using? Can you try it in a fresh conda environment?

**Comment by simoneggenschwiler** [comment]
I'm working on a mac with OS Mojave 10.14.6.
I have tried that and it doesn't make a difference.
Thank you for your very quick response!

**Comment by simoneggenschwiler** [comment]
I've tried it again and it seems to be working now. I don't know what the difference is. Thank you for your help.
