### ISSUE TITLE
data_evaluation is missing

### ISSUE THREAD

**Issue by sheljoy** [openvax/mhcflurry#169]
when to  `mhcflurry-downloads fetch data_evaluation`  from https://github.com/openvax/mhcflurry/releases/download/1.6.0/data_evaluation.20200209.tar.bz2, in fact the source file does not exist in 1.6.0 release repository.

**Comment by sheljoy** [comment]
when detch    
models_class1_pan from models_class1_pan.https://github.com/openvax/mhcflurry/releases/download/1.6.0/models_class1_pan.20200104.tar.bz2,
 the same issue appears.

**Comment by timodonnell** [comment]
Thanks for this. It should be fixed now in the 2.0.0 release.
