### ISSUE TITLE
mhcflurry-downloads fetch error

### ISSUE THREAD

**Issue by suraj-gattani** [openvax/mhcflurry#172]
I was trying to install mhcflurry inside a docker image (ubuntu os). I could pip install mhcflurry but later when I ran "mhcflurry-downloads fetch" it gave me the following error.

`Traceback (most recent call last):
  File "/usr/local/bin/mhcflurry-downloads", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/dist-packages/mhcflurry/downloads_command.py", line 123, in run
    command_functions[args.subparser_name](args)
  File "/usr/local/lib/python3.8/dist-packages/mhcflurry/downloads_command.py", line 183, in fetch_subcommand
    default = not args.download_name and info['metadata']['default']
KeyError: 'default'`

**Comment by Admera2020** [comment]
@suraj-gattani I am getting the same error, how did you resolve it?

**Comment by suraj-gattani** [comment]
I actually downloaded the class1-presentation model only and it started working for me.
I think you can download all of them separately and it should work for you as well.

**Comment by Admera2020** [comment]
Thanks a lot for the  response.

**Comment by timodonnell** [comment]
Oops, this was caused by a silly typo. I just pushed version 2.0.1 to PyPI to fix it. Let me know if you encounter it again.

**Comment by Admera2020** [comment]
Thanks, it's working now 👍
