### ISSUE TITLE
Illegal Hardware Instruction

### ISSUE THREAD

**Issue by as1000** [openvax/mhcflurry#183]
After installing the MHC flurry through pip and downloading the dataset/trained model. I attempted to run the example:

$ mhcflurry-predict \
       --alleles HLA-A0201 HLA-A0301 \
       --peptides SIINFEKL SIINFEKD SIINFEKQ \
       --out /tmp/predictions.csv

The run fails with:

zsh: illegal hardware instruction

On Spyder, although I can import Class1PresentationPredictor fine:

from mhcflurry import Class1PresentationPredictor

When I attempt to load the Class1PresentationPredictor, the Kernel restarts with "WARNING | No such comm":

predictor = Class1PresentationPredictor.load()

**Comment by timodonnell** [comment]
I'm not sure what would be causing this, but it is likely a tensorflow issue. What version of tensorflow is installed? Are you able to import tensorflow and run a trivial test script like `import tensorflow as tf ; print(tf.constant([5]) + tf.constant([3]))` ? Does it work if you install mhcflurry in a clean conda environment?

**Comment by as1000** [comment]
It seems to be a problem with Tensorflow. I think it has to do with a
