### ISSUE TITLE
Selenocysteine

### ISSUE THREAD

**Issue by p-priestley** [openvax/mhcflurry#184]
Hello, 

Thanks for the great tool.

Could you please advise whether you have any support for peptides with the Selenocysteine amino acid (normally represented as 'U') and if so how to specify this in the mhcflurry-predict command?

Peter

**Comment by timodonnell** [comment]
We do not, unfortunately.

I'd be interested to add this but we don't have much data for U-containing peptides to train on (IEDB seems to have just 3 seleno-peptides for class I). If you're aware of any data sources on MHC/seleno-peptide binding I'd be interested to know.

**Comment by p-priestley** [comment]
Sorry.  I am not aware of any validation data.      Thanks for the quick reply.
