### ISSUE TITLE
Difference between "affinity_percentile" and "presentation_percentile"

### ISSUE THREAD

**Issue by ShanWeera** [openvax/mhcflurry#193]
What is the difference between `affinity_percentile` and `presentation_percentile`?

**Comment by timodonnell** [comment]
presentation_percentile is the percentile rank of the presentation score (which combines MHC binding affinity and processing score). affinity_percentile is the percentile rank of the MHC binding affinity alone. Presentation score is experimental. If you are just looking for MHC binding predictions you should use affinity_percentile.
