### ISSUE TITLE
moving the directory for models_class1_presentation not posssible

### ISSUE THREAD

**Issue by aubreybailey** [openvax/mhcflurry#194]
When using the 'models_class1_presentation' combination model, it MUST be installed in ~/.local/share/.../models/ which may move around a bit if you are running as a daemon user, root, or as your own user. 
Any individual model can be run by specifying a directory that contains a manifest.csv, however the special (default) case of models_class1_presentation seems to run three models from a root directory (with no manifest.csv). 
The --models flag requires that we are specifying a manifest.csv directory. There doesn't seem to be a correct way to run the 3-part models_class1_presentation combination model using the --models flag.

I'm fixing the problem with symbolic links for now.

Super grateful for all the fantastic work. You're making a difference in the world!

**Comment by timodonnell** [comment]
The `--models` option to `mhcflurry-predict` can be passed the path to either a binding affinity predictor (i.e. a dir with manifest.csv) or a presentation  predictor (i.e. a dir with subdirectories like `affinity_predictor`, `processing_predictor_with_flanks`, `processing_predictor_without_flanks`, and a `weights.csv` file).

For example, you can specify a presentation predictor like this and you'll get affinity, processing, and presentation scores:

```
$ mhcflurry-predict --peptides SIINFEKL --alleles A*02:01 --models '/Users/tim/Library/Application Support/mhcflurry/4/2.0.0/models_class1_presentation/models'
...
allele,peptide,mhcflurry_affinity,mhcflurry_affinity_percentile,mhcflurry_processing_score,mhcflurry_presentation_score,mhcflurry_presentation_percentile
A*02:01,SIINFEKL,11927.162979797404,6.296000000000002,0.2647096160799265,0.02069020380677246,11.6303260869565
```

Or to just run binding affinity predictions, pass in the path to a binding affinity predictor, which we can do by passing in the `affinity_predictor` sub directory of the presentation predictor used above: 

```
$ mhcflurry-predict --peptides SIINFEKL --alleles A*02:01 --models '/Users/tim/Library/Application Support/mhcflurry/4/2.0.0/models_class1_presentation/models/affinity_predictor'
...
allele,peptide,mhcflurry_affinity,mhcflurry_affinity_percentile
A*02:01,SIINFEKL,11927.162979797404,6.296000000000002
```

Hope that helps.

**Comment by aubreybailey** [comment]
Nevermind. This works. I got all the way through typing this and realized that I forgot the add .../models at the end of the path. Posting anyways in case someone is searching.
Closed, thanks! Thanks for humoring my debugging.


Yes, that's exactly the problem I'm reporting. That demo doesn't function as advertised if you specify the --models flag at all.
Python 3.6.8, Centos 7

```bash
mkdir deleteme

cd deleteme/

virtualenv-3 mhcflurry_venv

source mhcflurry_venv/bin/activate

pip3 install mhcflurry

mhcflurry-downloads fetch models_class1_presentation

mkdir -p /home/aubrey.bailey/test_location/share/mhcflurry/4/2.0.0/

mv /home/aubrey.bailey/.local/share/mhcflurry/4/2.0.0/models_class1_presentation/ /home/aubrey.bailey/test_location/share/mhcflurry/4/2.0.0/

mhcflurry-predict --peptides SIINFEKL --alleles A*02:01 --models /home/aubrey.bailey/test_location/share/mhcflurry/4/2.0.0/models_class1_presentation
```

Results in:
```python
Traceback (most recent call last):
  File "/home/aubrey.bailey/deleteme/mhcflurry_venv/bin/mhcflurry-predict", line 8, in <module>
    sys.exit(run())
  File "/home/aubrey.bailey/deleteme/mhcflurry_venv/lib/python3.6/site-packages/mhcflurry/predict_command.py", line 207, in run
    affinity_predictor = Class1AffinityPredictor.load(models_dir)
  File "/home/aubrey.bailey/deleteme/mhcflurry_venv/lib/python3.6/site-packages/mhcflurry/class1_affinity_predictor.py", line 498, in load
    manifest_df = pandas.read_csv(manifest_path, nrows=max_models)
  File "/home/aubrey.bailey/deleteme/mhcflurry_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/aubrey.bailey/deleteme/mhcflurry_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/aubrey.bailey/deleteme/mhcflurry_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/aubrey.bailey/deleteme/mhcflurry_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/aubrey.bailey/deleteme/mhcflurry_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: '/home/aubrey.bailey/test_location/share/mhcflurry/4/2.0.0/models_class1_presentation/manifest.csv'
````
