### ISSUE TITLE
Non-standard amino acids (e.g. U for selenocysteine) result in failure in mhcflurry-predict-scan even when --no-throw passed

### ISSUE THREAD

**Issue by Hilly20211122** [openvax/mhcflurry#199]
Hi are there any suggestions on how to use the mhcflurry-predict-scan to read FASTA sequences containing selenoproteins that use selenium (Se) in place of sulfur (S)? Thanks.

**Comment by timodonnell** [comment]
Good question. My intention was that passing `--no-throw` would cause these peptides to be skipped but that doesn't seem to be the case. So we can consider this issue a bug. I think a fix shouldn't be too difficult.

**Comment by Hilly20211122** [comment]
Hi Tim, Thanks for your response. Am really enjoying using McFlurry it’s an awesome prediction tool. Lex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
