### ISSUE TITLE
error when using MHCflurry

### ISSUE THREAD

**Issue by robertoimuno** [openvax/mhcflurry#202]
I am trying to use mhcflurry which needs mhcgnomes and there is an error when trying to use Class2Pair in the script common.py. Apart from that I found a bug in the line 71 of the same script. The Allele object from mhcgnomes package does not have an attribute called restrict_num_allele_fields, they updated the package and now is called restrict_allele_fields.

Also when I try to install mhcflurry with conda using: `conda install -c bioconda mhcflurry` It installs the version 1.6 and I cannot install 2.0.1 even if that version is in the conda site
[mhcflurryIssue.txt](https://github.com/openvax/mhcflurry/files/8853080/mhcflurryIssue.txt)

**Comment by timodonnell** [comment]
The `Class2Pair` issue should be fixed now, please give it another try

**Comment by robertoimuno** [comment]
Hi @timodonnell thank you very much, now it seems to work. The version that you download using pip is still the old one but I guess that it takes some days to be updated.

Another question, is there a way with mhcflurry to avoid errors when the peptide sequence has non-common aminos like X

Thank you very much

**Comment by timodonnell** [comment]
Ok, PyPI should be updated now to have the latest version (2.0.6). Let me know if you still hit issues.

You can avoid most errors by passing `--no-throw` on the command line or `throw=False` in the Python predict interfaces.

**Comment by robertoimuno** [comment]
Everything works fine now, thank you very much. Just one last question:

When running mhcFlurry we get three main values that can be used to filter peptides that will be presented or not. The most used affinity threshold is 500nM or lower if I am not wrong, but do you also know which threshold should I consider for the antigen procesing score or for the presentation score  if I want to identify peptides that will be presented.

Thank you in advance

**Comment by timodonnell** [comment]
Sorry - we do not have a validated cutoff for presentation score. Something in the range of 1.0-5.0 presentation percentile rank is likely a reasonable cutoff but if you want something very well established I would just stick with 500 nM affinity prediction.

**Comment by robertoimuno** [comment]
Hi @timodonnell, your answer was very helpful, but I still have a question about the range for presentation percentile rank you gave me in the comment above.

By running mhcFlurry with many peptides I found what will be very good binders in terms of affinity (below 500nM) and no binders if I look a the presentation percentile value. Here is an example:

Peptide               Affinity        Presentation percentile
MLVELVRRI ---> 30,2 nM -----> 0,05


As you can see the value for the Presentation percentile is not included in the range you gave me (1 to 5). Could this be because, as you also commented, this range is not validated or because I am using the wrong value? Could it also be that the range goes from 0 to 5?, because I noticed that the very good binders (in terms of affinity) always have a presentation percentile under 1.

**Comment by timodonnell** [comment]
Ah yes - I meant using a *cutoff* in the range of 1.0-5.0 is reasonable. The overall range is 0 - 100 so values less than 1.0 are definitely possible (and are good binders).
