### ISSUE TITLE
Update mhcflurry on bioconda

### ISSUE THREAD

**Issue by jonasscheid** [openvax/mhcflurry#211]
Hey there,

I was curious if you might want to update MHCflurry on bioconda to the latest release, since the latest version is 2.0.6. That would be great, because then quay creates a biocontainer out of it automatically afaik and I could use it in a nextflow pipeline. I can also take care of this. Just let me know if you are fine with this, or how you would proceed here.

Best,
Jonas

**Comment by timodonnell** [comment]
Hi Jonas - thanks for offering this! It would be great if you are able to do the update. I haven't pushed anything to bioconda before so I'm not sure of the procedure. Let me know if you need us to do anything on our end for this.

**Comment by jonasscheid** [comment]
Ah its failing, because `mhcgnomes` is also not [existing](https://dev.azure.com/bioconda/bioconda-recipes/_build/results?buildId=26243&view=logs&j=e14e69ff-a0ae-55c4-b71d-229b239cfb2f&t=7df82132-b284-504b-53d6-7d3e63519572&l=592) in conda yet. Can you (or your colleague @iskandr, or whoever is maintaining this repo) make sure the github release versioning is in-line with the [pypi versions](https://pypi.org/project/mhcgnomes/1.8.4/#history)?
I'll try to upload the newest version of mhcgnomes to bioconda as well then

**Comment by timodonnell** [comment]
@iskandr any chance you can look into this?

Sorry for the slow replies here @jonasscheid

**Comment by jonasscheid** [comment]
No worries, would only be good to keep track of versions in a coherent way.
By the way the conda receipt got merged and one can install version 2.0.6 from [bioconda](https://anaconda.org/bioconda/mhcflurry) or use the docker container from [quay](https://quay.io/repository/biocontainers/mhcflurry) 👍 Here you don't have the tensorflow-problem with arm-architectures as far as I can see (and tested). So maybe a smoother way to install mhcflurry.

**Comment by tamuanand** [comment]
Hi @jonasscheid and @timodonnell 

A question: how does one use the quay.io biocontainer - I seem to get this error
```
docker run --rm  quay.io/biocontainers/mhcflurry:2.1.2--pyh7e72e81_0 mhcflurry-predict --peptides SIINFEKL --alleles HLA-A*02:01                                                                                      Traceback (most recent call last):
  File "/usr/local/bin/mhcflurry-predict", line 10, in <module>
    sys.exit(run())
             ^^^^^
  File "/usr/local/lib/python3.12/site-packages/mhcflurry/predict_command.py", line 200, in run
    models_dir = get_default_class1_presentation_models_dir(test_exists=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mhcflurry/downloads.py", line 122, in get_default_class1_presentation_models_dir
    return get_path(
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/mhcflurry/downloads.py", line 223, in get_path
    raise RuntimeError(
RuntimeError: Missing MHCflurry downloadable file: /root/.local/share/mhcflurry/4/2.2.0/models_class1_presentation/models. To download this data, run:
        mhcflurry-downloads fetch models_class1_presentation
in a shell.

```

Thanks in advance.

**Comment by jonasscheid** [comment]
As the error messages says, you need to first download the models into the docker container using the suggest command. Afterward you should be able to run the prediction. Use docker flag -it to interactively navigate in the container.

**Comment by jonasscheid** [comment]
Did that help?
