### ISSUE TITLE
Use yaml.safe_load for training scripts

### ISSUE THREAD

**Issue by ernesto-elsaesser** [openvax/mhcflurry#215]
https://github.com/openvax/mhcflurry/pull/142 updated the YAML loading in the `download` module.

But the training scripts still use `yaml.load` instead of `yaml.safe_load`, e.g.:
https://github.com/openvax/mhcflurry/blob/master/mhcflurry/train_allele_specific_models_command.py#L145
https://github.com/openvax/mhcflurry/blob/master/mhcflurry/train_pan_allele_models_command.py#L306

With PyYAML 6.0 (released in 2021) this does not just print a warning, but crashes with an error.
Could you adjust these scripts accordingly?

**Comment by timodonnell** [comment]
Thanks for noting this - will take a look
