### ISSUE TITLE
where is the np-utils dependency used?

### ISSUE THREAD

**Issue by samuela** [openvax/mhcflurry#216]
Hi, while packaging mhcflurry for nixpkgs, I noticed that np-utils is declared as a dependency, but does not appear to be imported anywhere AFAICT: https://github.com/search?q=repo%3Aopenvax%2Fmhcflurry+np_utils&type=code

Where is this dependency used? Is it vestigial?

**Comment by timodonnell** [comment]
Thanks - it does seem vestigial
