### ISSUE TITLE
is it possible to use mhcflurry for fish mhc prediction?

### ISSUE THREAD

**Issue by najibveto** [openvax/mhcflurry#218]
hello,
I am a bit curious, while i was running the command:
`mhcflurry-predict --list-supported-alleles`
i got a list of alleles for fish (atlantic salmon):
`Sasa-UBA*01:01
Sasa-UBA*02:01
Sasa-UBA*03:01
Sasa-UBA*03:02
Sasa-UBA*04:01
Sasa-UBA*04:02
Sasa-UBA*05:01
Sasa-UBA*06:01
Sasa-UBA*06:02
Sasa-UBA*06:03
Sasa-UBA*07:01
Sasa-UBA*08:01
Sasa-UBA*09:01
Sasa-UBA*10:01
Sasa-UBA*11:01
Sasa-UBA*12:01
Sasa-UBA*13:01
Sasa-UBA*14:01
Sasa-UBA*15:01
Sasa-UBA*16:01
Sasa-UBA*17:01
Sasa-UBA*18:01
Sasa-UBA*18:02
Sasa-UBA*19:01
Sasa-UBA*20:01
Sasa-UBA*20:02
Sasa-UBA*21:01
Sasa-UBA*22:01
Sasa-UBA*23:01
Sasa-UBA*24:01
Sasa-UBA*24:02
Sasa-UBA*24:03
Sasa-UBA*25:01
Sasa-UBA*26:01
Sasa-UBA*26:02
Sasa-UBA*27:01
Sasa-UBA*28:01
Sasa-UBA*29:01
Sasa-UBA*30:01
Sasa-UBA*31:01
Sasa-UBA*32:01
Sasa-UBA*33:01
Sasa-UBA*34:01
Sasa-UBA*34:02
Sasa-UBA*35:01
Sasa-UBA*36:01
Sasa-UBA*37:01
Sasa-UBA*38:01
Sasc-G*04:01`
is it possible to predict epitope using salmon alleles?

**Comment by timodonnell** [comment]
It will certainly run with these alleles and give you predictions. The accuracy is uncertain however. Curious how it goes for you if you give this a shot.
