### ISSUE TITLE
How to configure models path?

### ISSUE THREAD

**Issue by WShaoLab** [openvax/mhcflurry#233]
Hi

Thanks for your work in mhcflurry. I installed mhcflurry by conda and the MHCflurry downloadable file was located in /home/usr/.local/share/mhcflurry/4/2.0.0/models_class1_presentation/models by default. But there is no space left in my home folder.

I am writing to ask for help, how can I set a different path for the models?
Thanks very much!

Best regards
xiaoxiang

**Comment by timodonnell** [comment]
Hey, you should be able to get around this by setting the `MHCFLURRY_DATA_DIR` environment variable to a path where you have more space.

**Comment by WShaoLab** [comment]
oh, I got this problem solved. Thanks very much!

Best wishes
