### ISSUE TITLE
[request]: update Docker image to version 2.1.2

### ISSUE THREAD

**Issue by tamuanand** [openvax/mhcflurry#242]
Hi @timodonnell 

Thanks for the great tool. I was wondering if you would be able to provide a latest docker image of the tool with version 2.1.2 
- the current one at dockerhub is 10 months old - I am guessing it is version 2.1.0 from Oct 2023 - https://github.com/openvax/mhcflurry/releases/tag/v2.1.0

I am assuming that the docker image has the underlying datasets too - I am primarily looking to `docker run --rm -it mhcflurry:latest mhcflurry-predict` and not as a Jupyter notebook as mentioned here

Thanks in advance.

**Comment by timodonnell** [comment]
Sure, good idea. I just pushed an updated image to dockerhub ([openvax/mhcflurry:latest](https://hub.docker.com/layers/openvax/mhcflurry/latest/images/sha256-5fe30f546dbf271eda5b4decb533ca5aeae9a271ea625114a27a739ce442d3df?context=repo)). And you are correct that it includes the models in the image.
