### ISSUE TITLE
Version 2.1.3 on PyPI?

### ISSUE THREAD

**Issue by ndalchau** [openvax/mhcflurry#243]
If version 2.1.3 is now considered released, can you publish it to PyPI please? Currently, the latest published is 2.1.2: https://pypi.org/project/mhcflurry/
Many thanks!

**Comment by ndalchau** [comment]
I can see that this is because of an Action failure: https://github.com/openvax/mhcflurry/actions/runs/10976027992

**Comment by ndalchau** [comment]
Just need to upgrade `actions/download-artifact`

**Comment by timodonnell** [comment]
Thanks - any advice on this actually? I bumped actions/download-artifact to version 4 but still seeing the failure.

**Comment by ndalchau** [comment]
Oh yes, I see you've already upgraded to v4. The last time the `release` workflow passed, it was running v2, so this specific workflow might not be set up correctly. But you've got the sister method `upload-artifact` running with v4 on the `build` workflow.

I've never actually used the artifact mechanism in any of the actions I've worked with, so I probably won't be much help than that, but what I'd try next would be:
- Change `v4.1.7` to `v4`
- Remove line 24: `path: dist`

Otherwise, maybe @jday1 might be able to help.

**Comment by ndalchau** [comment]
Ah-ha, it worked. Well done :)
