### ISSUE TITLE
push automatically to PyPI on new release

### ISSUE THREAD

**Issue by timodonnell** [openvax/mhcflurry#53]

**Comment by julia326** [comment]
will also push out a new release as part of this

**Comment by timodonnell** [comment]
@julia326 is this something you're still interested in sorting out? Feel free to unassign yourself if not

**Comment by julia326** [comment]
Sure! Going to do this for a bunch of repos including this one. While I'm there, any interest in me adding unit tests for any other repos to the Travis pre-release script?

**Comment by timodonnell** [comment]
Closing this. For this project I think it's better to do releases manually due to the interaction with the externally downloaded data (pretrained models etc). Doing releases manually gives an extra opportunity to test that the correct models are being used before pushing to pypi
