### ISSUE TITLE
add a mhcflurry-score tool

### ISSUE THREAD

**Issue by timodonnell** [openvax/mhcflurry#55]
This should take the output CSV of `mhcflurry-predict` and compute AUC, F1, and Kendall's Tau scores

**Comment by timodonnell** [comment]
No longer really needed (and would be more complicated to do now that we have training data with inequalities as well as mass-spec)

**Comment by saskra** [comment]
Actually, I still would like to have something like that to compare different topologies, sets of hyperparameters and other algorithms.
